-- Prototype schema (no auth yet — see README "Architecture / roadmap").
-- When real login lands (Supabase Auth per the future-state branch of the
-- diagram), `documents.owner_id` is where a user id would attach; for now
-- documents are anonymous and only reachable by their random id.

CREATE TABLE IF NOT EXISTS documents (
  id          TEXT PRIMARY KEY,        -- random id, generated by the Worker
  created_at  TEXT NOT NULL,           -- ISO 8601
  updated_at  TEXT NOT NULL,           -- ISO 8601
  owner_id    TEXT,                    -- NULL until real accounts exist
  title       TEXT,                    -- e.g. the memo's "เรื่อง" (subject), for a future list view
  data        TEXT NOT NULL            -- JSON blob: the full form/document state
);

CREATE INDEX IF NOT EXISTS idx_documents_owner_id ON documents(owner_id);

-- Sliding-window counters for the basic per-IP rate limit on the
-- unauthenticated /api/draft and /api/chat endpoints.
CREATE TABLE IF NOT EXISTS rate_limit_hits (
  bucket_key  TEXT NOT NULL,           -- e.g. "<ip>:<route>"
  hit_at      TEXT NOT NULL            -- ISO 8601
);

CREATE INDEX IF NOT EXISTS idx_rate_limit_hits_bucket_key ON rate_limit_hits(bucket_key, hit_at);
